name : release

on :
  workflow_dispatch 
  
jobs:
  release:
    name: 自动release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version : latest
          run_install : true

      - name: get version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: 打包userscript
        run: pnpm run build:js
        
      - name: 发布userscript
        uses: softprops/action-gh-release@v1
        with:
          tag_name :  ${{ steps.package-version.outputs.current-version}}
          files: ./dist/*.js
          
      # 发布extension
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: pip install python-dotenv
        
      - name : 生成manifest.json
        run: python ./scripts/metadata.py
          
      - name : build extension
        run: pnpm run build:crx
        
      - name : zip
        run : python ./scripts/zip.py
        
      - name : 发布extension
        uses: softprops/action-gh-release@v1
        with:
          tag_name :  ${{ steps.package-version.outputs.current-version}}
          files: ./dist/*.zip
      

